project : "Data_DietXDST"
device : "cuda"

data: 
  name : "cifar10"
  batch_size: 128
  num_workers: 8
  num_classes: 10
  iteration : 7800
model:
  name : "ResNet20"
  
  rewind_frequency : 100
training:
  mode : "sparse"
optimizer:
  type: SGD
  lr: 0.08
  momentum: 0.9
  weight_decay: 0.0005
epochs : 200
